[package]
name = "rust"
version = "1.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[dependencies]
serde_json = "1.0.2"
serde = "1.0.8"
serde_derive = "1.0.8"
reqwest = "0.8"
chrono = {version = "0.4", features = ["serde"]}
