[light]
primary_0="#E74763"
primary_1="#FE92A5"
primary_2="#F7657F"
primary_3="#A32A3F"
primary_4="#40131B"

//.color-secondary-1-0 { color: #F7DC4C; }
//.color-secondary-1-1 { color: #FFEE93; }
//.color-secondary-1-2 { color: #FFE869; }
//.color-secondary-1-3 { color: #AD992D; }
//.color-secondary-1-4 { color: #443D14; }

//.color-secondary-2-0 { color: #5E41A9; }
//.color-secondary-2-1 { color: #B49AF8; }
//.color-secondary-2-2 { color: #8566D7; }
//.color-secondary-2-3 { color: #3E2877; }
//.color-secondary-2-4 { color: #19112F; }

//.color-complement-0 { color: #6DD441; }
//.color-complement-1 { color: #B1FC91; }
//.color-complement-2 { color: #8BED61; }
//.color-complement-3 { color: #479526; }
//.color-complement-4 { color: #1D3B11; }
