[package]
name = "reproto"
version = "0.3.19"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto"
description = """
reproto compiler
"""

[features]
# Enable to emit very detailed tracing, potentially performance sensitive.
tracing = []

[dependencies]
reproto-core = {path = "../lib/core", version = "0.3"}
reproto-trans = {path = "../lib/trans", version = "0.3"}
reproto-ast = {path = "../lib/ast", version = "0.3"}
reproto-semck = {path = "../lib/semck", version = "0.3"}
reproto-derive = {path = "../lib/derive", version = "0.3"}
reproto-compile = {path = "../lib/compile", version = "0.3"}
reproto-manifest = {path = "../lib/manifest", version = "0.3"}
reproto-parser = {path = "../lib/parser", version = "0.3"}
reproto-repository = {path = "../lib/repository", version = "0.3"}
reproto-repository-http = {path = "../lib/repository-http", version = "0.3"}
reproto-backend = {path = "../lib/backend", version = "0.3"}
reproto-backend-csharp = {path = "../lib/backend-csharp", version = "0.3"}
reproto-backend-doc = {path = "../lib/backend-doc", version = "0.3"}
reproto-backend-go = {path = "../lib/backend-go", version = "0.3"}
reproto-backend-java = {path = "../lib/backend-java", version = "0.3"}
reproto-backend-js = {path = "../lib/backend-js", version = "0.3"}
reproto-backend-json = {path = "../lib/backend-json", version = "0.3"}
reproto-backend-python = {path = "../lib/backend-python", version = "0.3"}
reproto-backend-reproto = {path = "../lib/backend-reproto", version = "0.3"}
reproto-backend-rust = {path = "../lib/backend-rust", version = "0.3"}
reproto-backend-swift = {path = "../lib/backend-swift", version = "0.3"}

ansi_term = "0.9"
atty = "0.2"
clap = "2.24"
linked-hash-map = {version = "0.5", features = ["serde"]}
log = "0.3"
pulldown-cmark = "0.0.14"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
url = "1.6"
url_serde = "0.2"
genco = {version = "0.3"}
